exec DBMS_SCHEDULER.DISABLE('PURGE_LOG');
exec DBMS_SCHEDULER.DISABLE('BSLN_MAINTAIN_STATS_JOB');
exec DBMS_SCHEDULER.DISABLE('ORA$AUTOTASK_CLEAN');
exec DBMS_SCHEDULER.DISABLE('ORACLE_OCM.MGMT_STATS_CONFIG_JOB');
exec DBMS_SCHEDULER.DISABLE('ORACLE_OCM.MGMT_CONFIG_JOB');
exec DBMS_SCHEDULER.DISABLE('DRA_REEVALUATE_OPEN_FAILURES');
