host echo -n -e "\e[0;31m+=======================+Recovery===============================================================+\e[0m"
host echo -n -e "\e[0;31m|hcheck.sql             |用户特殊恢复（比如active redo故障恢复后）数据字典一致性检查    \e[0m "     
host echo -n -e "\e[0;31m+=======================+其他配置方面===========================================================+\e[0m"
host echo -n -e "\e[0;33m|检查数据库_use_adaptive_log_file_sync配置是否合理: select upper(value) VALUE from v\$parameter where name ='_use_adaptive_log_file_sync';参数 _use_adaptive_log_file_sync 11.2.0.3版本及以上版本的参数默认为TRUE，可能影响日志同步性能, 建议生产库做以下调整(参考MOS 文档： 1462942.1 )： alter system set "_use_adaptive_log_file_sync"=false; \e[0m"
host echo -n -e "\e[0;32m|_undo_autotune配置是否合理: select upper(value) VALUE from v\$parameter where name ='_undo_autotune'; 可能出现UNDO表空间利用率过高或者是UNDO段争用的问题,建议生产库做以下调整(相关故障可参考MOS 文档： 1574714.1 )： alter system set “_undo_autotune” = false;\e[0m"
host echo -n -e "\e[0;31m|参数deferred_segment_creation为TRUE,可能出现如exp,imp导入导出BUG,表空间删除后对应的表对象还在数据字典等问题, select upper(value) VALUE from v\$parameter where name ='deferred_segment_creation';建议生产库设置为false(相关故障可参考MOS 文档:1216282.1 )\e[0m"
host echo -n -e "\e[0;29m|参数control_file_record_keep_time建议大于15,否则控制文件里可重复使用的记录偏少，备份恢复时可能需要额外操作, select value from v\$parameter where name ='control_file_record_keep_time';建议生产库适当增大该值(参考MOS 文档47322.1)\e[0m"
host echo -n -e "\e[0;31m|参数 _datafile_write_errors_crash_instance为TRUE,不符合最佳实践,数据库可能因为IO错误影响而意外终止,数据库稳定性较低, select value from v\$parameter where name ='_datafile_write_errors_crash_instance';DBWR进程写出到数据文件遇到I/O问题时的表现:在版本11g中:1. 默认情况下，若是RAC或未启用归档的实例或出现问题的是SYSTEM表空间的数据文件会导致实例终止;其他情况下,会造成相关数据文件被OFFLINE。2.若该参数设置为TRUE，则在DBWR写文件出现问题时总是终止本实例 3. 若设置为FALSE，仅在未启用归档或SYSTEM表空间的数据文件的情况下会终止实例\e[0m"
host echo -n -e "\e[0;27m|    \e[0m"
